# Generated by Django 4.0.4 on 2022-05-05 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
