# Generated by Django 4.0.4 on 2022-05-05 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0005_alter_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('L', 'Leader'), ('M', 'Member')], max_length=1)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserRole_team', to='tasktracker.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRole_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
