# Generated by Django 4.0.4 on 2022-05-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0006_remove_customuser_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRole_team', to='tasktracker.team'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'team', 'role'), name='A User can only have one role in a Team'),
        ),
    ]
